use_frameworks!

def tealium_libs
  pod 'tealium-prism/Core', :path => '../'
  pod 'tealium-prism/Lifecycle', :path => '../'
  pod 'tealium-prism/MomentsAPI', :path => '../'
end

target 'Example_iOS' do
  platform :ios, '14.1'
  tealium_libs
  end

target 'CoreTests_iOS' do
  platform :ios, '14.1'
  tealium_libs
end

target 'CoreTests_macOS' do
  platform :osx, '10.15'
  tealium_libs
end

target 'CoreTests_watchOS' do
  platform :watchos, '7.0'
  tealium_libs
end

target 'CoreTests_tvOS' do
  platform :tvos, '14.1'
  tealium_libs
end

target 'EndToEndTests_iOS' do
  platform :ios, '14.1'
  tealium_libs
end

target 'EndToEndTests_macOS' do
  platform :osx, '10.15'
  tealium_libs
end

target 'EndToEndTests_tvOS' do
  platform :tvos, '14.1'
  tealium_libs
end

target 'EndToEndTests_watchOS' do
  platform :watchos, '7.0'
  tealium_libs
end

target 'DelegateProxyTests_iOS' do
  platform :ios, '14.1'
  tealium_libs
end

target 'LifecycleTests_iOS' do
  platform :ios, '14.1'
  tealium_libs
end

target 'LifecycleTests_tvOS' do
  platform :tvos, '14.1'
  tealium_libs
end

target 'LifecycleTests_macOS' do
  platform :osx, '10.15'
  tealium_libs
end

target 'LifecycleTests_watchOS' do
  platform :watchos, '7.0'
  tealium_libs
end

target 'MomentsAPITests_iOS' do
  platform :ios, '14.1'
  tealium_libs
end

target 'MomentsAPITests_macOS' do
  platform :osx, '10.15'
  tealium_libs
end

target 'MomentsAPITests_watchOS' do
  platform :watchos, '7.0'
  tealium_libs
end

target 'MomentsAPITests_tvOS' do
  platform :tvos, '14.1'
  tealium_libs
end

post_install do |installer|
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Tealium, Inc"
end
