use_frameworks!

platform :ios, '11.0'

target 'tealium-swift_Example' do
  pod 'tealium-swift', :path => '../'

end


target 'tealium-swift_Tests' do
  pod 'tealium-swift', :path => '../'

end

post_install do |installer|
    installer.pods_project.root_object.attributes["ORGANIZATIONNAME"] = "Tealium, Inc"
end
