modules: 
- TealiumPrismCore
- TealiumPrismLifecycle
title: TealiumPrism
author: Tealium
author_url: https://www.tealium.com
source_host_url: https://github.com/tealium/tealium-prism-swift
readme: .README.md
exclude:
  - "**/Internal*"
sdk: iphoneos
swift_build_tool: spm
abstract: 'docs/sections/**.md'
documentation: 'docs/guides/**.md'

custom_categories: 
  - name: Tealium
    children:
    - Tealium
    - TealiumConfig
    - TealiumInstanceManager
    - regex: ^CoreSettings
  - name: Modules
    children:
    - Modules
    - AppData
    - Collect
    - ConnectivityData
    - DataLayer
    - DeepLinkHandler
    - DeviceData
    - Lifecycle
    - TealiumData
    - TimeData
    - Trace
  - name: AppData Module
    children:
    - regex: ^AppData
  - name: ConnectivityData Module
    children:
    - regex: ^ConnectivityData
  - name: Consent
    children:
    - regex: Consent
    - regex: CMP
  - name: Collect Module
    children:
    - regex: CollectSettings
  - name: DataLayer Module
    children:
    - regex: ^DataLayer
  - name: DeepLinkHandler Module
    children:
    - regex: DeepLink
    - Referrer
  - name: DeviceData Module
    children:
    - regex: DeviceData
  - name: Lifecycle Module
    children:
    - regex: Lifecycle
  - name: TealiumData Module
    children:
    - regex: TealiumData
  - name: TimeData Module
    children:
    - regex: TimeData
  - name: Rules
    children:
    - regex: Rule
    - regex: Condition
  - name: Barriers
    children:
    - Barriers
    - regex: Barrier
  - name: Transformations
    children:
    - regex: Transformation
  - name: Module
    children:
    - Module
    - regex: Module
    - regex: Collector
    - regex: Dispatcher
    - regex: Transformer
    - regex: Mapping
  - name: Data
    children:
    - regex: ^Data
    - Expiry
    - regex: ^Dispatch
    - regex: ^JSON
    - regex: Root
    - ReferenceContainer
    - ValueContainer
  - name: PubSub
    children:
    - regex: Observable
    - regex: Publisher
    - regex: Subject
    - regex: ^(?!.*Signpost).*State.*
    - regex: Single
    - regex: Dispos
    - regex: Subscri
  - name: Network
    children:
    - regex: Network
    - regex: HTTP
    - regex: Interceptor
    - ObjectResult