modules:
  - TealiumPrismCore
  - TealiumPrismLifecycle
  - TealiumPrismMomentsAPI
title: TealiumPrism
author: Tealium
author_url: https://www.tealium.com
source_host_url: https://github.com/tealium/tealium-prism-swift
readme: .README.md
exclude:
  - "**/Internal*"
sdk: iphoneos
swift_build_tool: spm
abstract: 'docs/abstracts/**/**.md'
documentation: 'docs/guides/**.md'

custom_categories:
  - name: Tealium
    children:
      - Tealium
      - TealiumConfig
      - TealiumError
      - TealiumInstanceManager
      - regex: ^CoreSettings
  - name: Modules
    children:
      - Modules
      - AppData
      - Collect
      - ConnectivityData
      - DataLayer
      - DeepLinkHandler
      - DeviceData
      - Lifecycle
      - MomentsAPI
      - TealiumData
      - TimeData
      - Trace
      - CustomModules
  - name: AppData Module
    children:
      - regex: ^AppData
  - name: Collect Module
    children:
      - regex: CollectSettings
  - name: ConnectivityData Module
    children:
      - regex: ^ConnectivityData
  - name: Consent
    children:
      - regex: ^Consent
      - regex: CMP
  - name: DataLayer Module
    children:
      - regex: ^DataLayer
  - name: DeepLinkHandler Module
    children:
      - regex: ^DeepLink
      - Referrer
  - name: DeviceData Module
    children:
      - regex: ^DeviceData
  - name: Lifecycle Module
    children:
      - regex: ^Lifecycle
  - name: MomentsAPI Module
    children:
      - regex: ^MomentsAPI
      - EngineResponse
  - name: TealiumData Module
    children:
      - regex: ^TealiumData(?!Key)
  - name: TimeData Module
    children:
      - regex: ^TimeData
  - name: Trace Module
    children:
      - regex: ^Trace
  - name: Rules
    children:
      - regex: Rule
      - regex: Condition
      - regex: Match
  - name: Barriers
    children:
      - Barriers
      - regex: Barrier
  - name: Transformations
    children:
      - regex: Transformation
  - name: Module
    children:
      - Module
      - regex: Module
      - regex: Collector
      - regex: Dispatcher
      - TealiumContext
      - regex: Transformer
      - regex: Mapping
  - name: Data
    children:
      - regex: ^Data
      - Expiry
      - regex: ^Dispatch
      - regex: ^JSON
      - regex: Root
      - ReferenceContainer
      - ValueContainer
      - regex: ^Any
  - name: PubSub
    children:
      - regex: Observable
      - regex: Publisher
      - regex: Subject
      - regex: ^(?!.*Signpost).*State.*
      - regex: Single
      - regex: Dispos
      - regex: Subscri
      - ValueExtractor
  - name: Network
    children:
      - regex: Network
      - regex: ConnectivityManager
      - regex: HTTP
      - regex: Interceptor
      - regex: Refresh
      - regex: Resource
      - regex: Retry
      - regex: URL
      - ErrorCooldown
      - ObjectResponse
      - ObjectResult
  - name: Logging
    children:
      - regex: Log
      - regex: Signpost
